### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'aria2c': 'aria2c'

### ISSUE THREAD

**Issue by mrjavadseydi** [Omkar47/AutoLeecher#8]
`26-Aug-21 06:21:49 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: 'aria2c': 'aria2c'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/AutoLeecher/apdbot/plugins/incoming_msg.py", line 60, in incoming_msg
    aria_i_p = await aria_start()
  File "/root/AutoLeecher/apdbot/helpers/download_aria.py", line 55, in aria_start
    stderr=asyncio.subprocess.PIPE
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'aria2c': 'aria2c'
`

**Comment by rishabhmodi03** [comment]
same error
